js_import conf.d/echo.js;

server {
	listen 10001;
	access_log off;

	location /books/ {
		root conf.d;
		random_index on;
	}
		
	location = /echo {
		js_content echo.echo;
		default_type application/json;
	}
}
