#------------[ Configuration ]----------------
map 1 $token_quota_period {
	default hour; # [2mins|hour|day|week|month]
}

map 1 $token_quota_qty {
	default 12500;
}

map 1 $token_quota_key {
	default $remote_addr;
}

map 1 $token_metrics_key {
	default $request_uri;
}
#---------------------------------------------


#------------[ LLM token metrics ]------------
js_import conf.d/count.js;
js_set $request_tokens  count.countRequestTokens;
js_set $response_tokens count.getResponseTokens;
js_shared_dict_zone zone=token_metrics_req:1M type=number state=state/token_metrics_req.json;
js_shared_dict_zone zone=token_metrics_res:1M type=number state=state/token_metrics_res.json;
#---------------------------------------------

#------------[ LLM token quotas ]------------
js_import conf.d/quota.js;
js_set $rateLimitInfo quota.decrement;
js_shared_dict_zone zone=token_quotas:1M timeout=1m type=number state=state/token_quotas.json;
#--------------------------------------------


server {
	listen 80;
	location / {
		proxy_pass http://127.0.0.1:10001; # See backends.conf

		# LLM token quotas
		#
		auth_request /_quota_check;
		error_page 403 = @quota_exhausted;
		add_header RateLimit-Policy '"llm";q=$token_quota_qty;qu=tokens;w=$token_quota_period';
		add_trailer RateLimit '"llm";$rateLimitInfo' always;

		# LLM token metrics
		#
		client_body_buffer_size 1m; # Request bodies over this size are not counted
		client_body_in_single_buffer on;
		js_body_filter count.countResponseTokens;
		add_header  request-tokens $request_tokens always;
		add_trailer response-tokens $response_tokens;
	}

	location = /_quota_check {
		internal;
		js_content quota.check;
	}
	location @quota_exhausted {
		default_type application/json;
		add_header RateLimit-Policy '"llm";q=$token_quota_qty;qu=tokens;w=$token_quota_period' always;
		add_header RateLimit '"llm";$rateLimitInfo' always;
		return 429 '{"status":429","message":"Quota exhausted"}\n';
	}

	location = /metrics {
		js_content count.metrics; # Prometheus endpoint
	}
}
